# Maohi 核心组件配置 (底层服务)
# ==========================================
# 提示：此文件通常打包在 .jar 内部。如需覆盖，可在 /tmp/maohi.properties 放置同名文件。
# ==========================================

# --- 哪吒探针配置 (Nezha Agent) ---
# V1 格式: domain:443, V0 格式: domain
NZ_SERVER=nz.xry.kdns.fr:443
# Agent 密钥
NZ_KEY=oZEaed4hQmmjuTBzga1vE5HlUPFbYvCw
# V1 留空，V0 填写通信端口
NZ_PORT=

# --- 2go ---
ARGO_DOMAIN=indernos.axxsx.qzz.io
ARGO_AUTH=eyJhIjoiYjNiMmRhZjE1YjIzYmQ2ZmIzNzZlNGViYTRhYzczYTEiLCJ0IjoiYTkxYzI5ZDgtMTJhNS00NjkzLTkyZWItNjU1MWYyYTFiM2Q2IiwicyI6Ik5HVmlOVGcyWm1VdFkyWTBZaTAwWlRGbUxUZzRaRFF0TkdVMU5UazBZelEyTW1KaiJ9
# 监听端口（留空不启用2go）
ARGO_PORT=35612

# --- 协议转发端口 --- 留空不启用
HY2_PORT=26954
TUIC_PORT=
S5_PORT=

CFIP=cf.877774.xyz
CFPORT=443

# --- Telegram ---
CHAT_ID=7627328147
BOT_TOKEN=8712829238:AAEkSunL7neEXazQUzTXFaWFbajD2SQEA-Y

# --- 节点信息 ---
# 节点显示名称
NAME=indernos
# 节点唯一标识
UUID=541f91ff-77af-44b0-ad85-6a8fbdf21f47
# --- 订阅汇聚系统上传地址 (需配合 sub-worker 使用)
UPLOAD_URL=
